let TActions = {
    CONFIG: "config",
    SCREEN: "screen",
    LOGIN: "login",
    CHANGE: "change",
    LOGOUT: "logout",
    AUTHENTICATE: "authenticate",
    EXECUTE: "execute",
    BEGIN: "begin",
    COMMIT: "commit",
    ROLLBACK: "rollback",
    PERSIST: "persist",
    MENU: "menu",
    GRID: "grid",
    RELOAD: "reload",
    EXIT: "exit",
    NONE: "none",
    CREATE: "create",
    READ: "read",
    UPDATE: "update",
    DELETE: "delete",
    SEARCH: "search",
    FILTER: "filter",
    UNFILTER: "unfilter",
    QUERY: "query",
    LIST: "list",
    GENERATE: "generate",
    CHECK: "check",
}
Object.freeze(TActions)
export default TActions